language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y automake libtool libsnmp-dev bison make gcc flex snmp-mibs-downloader
  - ./autogen.sh

script: 
  - ./configure && make && sudo make install
  - cd tests/
  - ../src/docsis -e docsis1_0_2class_non_rfc2669.txt key docsis1_0_2class_non_rfc2669.cm
  - ../src/docsis -d docsis1_0_2class_non_rfc2669.cm
#  - ./RunTests.sh
