os: osx

language: c

before_install:
  - sudo port install autoconf automake libtool glib2-devel bison flex net-snmp
  - sudo pip install cpp-coveralls
  - ./autogen.sh

script: 
  - ./configure CFLAGS='-g -O0 -fprofile-arcs -ftest-coverage'
  - make && sudo make install
  - cd tests/
  - ./RunTests.sh
  - cd ..

after_success:
  - coveralls --exclude src/docsis_lex.c --exclude src/docsis_yy.c --gcov-options '\-lp'
